### PR TITLE
Changing python3 to python.

### PR DESCRIPTION
**Pull request by jlconlin**

### CODE REVIEW

**Comment by jlconlin** [comment]
Anybody want to chime in on this?

**Comment by apmccartney** [comment]
I'll take a peak on the plane

**Comment by apmccartney** [comment]
Have you tested this using python 2.7?

**Comment by jlconlin** [comment]
I have not tested this using Python 2.7. I'll try and do that today sometime.

**Comment by nicholas-sly** [comment]
If not, you can modify the CMakeLists.txt file to specify a minimum version of python.  

find_package( PythonInterp 3.4 )

I have this change in my metaconfigure branch in the cmake.py file, but this will work in the short term until that is merged in.

**Comment by jlconlin** [comment]
I think we should specify a minimum Python version (2.7) but that is independent of this issue. This script is called before CMake so Make couldn’t enforce a Python version.

Jeremy


On Nov 1, 2017, at 9:53 AM, Nicholas Sly <notifications@github.com<mailto:notifications@github.com>> wrote:


If not, you can modify the CMakeLists.txt file to specify a minimum version of python.

find_package( PythonInterp 3.4 )

I have this change in my metaconfigure branch in the cmake.py file, but this will work in the short term until that is merged in.

**Comment by nicholas-sly** [comment]
Makes sense.

**Comment by jlconlin** [comment]
I verified that metaconfigure/generate.py works under Python 2.7. That is, It generated a CMakeLists.txt file without throwing any errors/warnings and I was able to compile and run all the tests with it.

**Pull request merged**
