### PR TITLE
Adding C++17 as C++ standard option.

### PR DESCRIPTION
**Pull request by jlconlin**
Pretty straightforward

### CODE REVIEW

**Comment by staleyLANL** [comment]
Yes! I was just thinking about this very issue earlier this afternoon, when I noticed that changing std::experimental::variant to std::variant, in knoop, didn't work. Great minds think alike. I say go ahead and merge as soon as you want.

**Comment by jlconlin** [comment]
Thanks @staleyLANL. Keep in mind that now we have to do a subtree pull into all of our repositories. (But only when we are touching the repositories anyway.)

**Comment by jlconlin** [comment]
@staleyLANL If you approve, please do a review and click the approve box. Yes, as administrator, I can do this regardless. However, I try not to abuse my authorities.

**Review by staleyLANL — APPROVED** [review]
Looks good. I just did a git grep '\<14\>' to be sure those four changes looked like the only necessary ones. All appears to be in order.

**Pull request merged**
