### PR TITLE
Start of documentation

### PR DESCRIPTION
**Pull request by jlconlin**

### CODE REVIEW

**Comment by apmccartney** [comment]
Does this compile to a webpage?

**Comment by jlconlin** [comment]
Yes it does. In the same vein as https://njoy.github.com/NJOY21

**Comment by apmccartney** [comment]
How do I see the rendered page?

**Comment by jlconlin** [comment]
You can install Jekyll on your machine. Or you can simply view the markdown pages on GitHub. It doesn't show all the formatting, but it gets part way there.

**Review by apmccartney — APPROVED** [review]

**Pull request merged**
